/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.HashSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import model.Acao;
import model.TickersAcao;
import modelDAO.AtivoDAO;


/// JSON:
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Ativo;
import model.Transacao;
import modelDAO.TransacaoDAO;
import modelReferencias.DadosAcao;
import util.Utilitarios;

/**
 *
 * @author vinic
 */
public class CadastroAcaoJD extends javax.swing.JDialog {
    
    private Acao acao;
    private boolean modoEdicao = false;

    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();

    /**
     * Creates new form CadastroInvestimentoJD
     */
    
    // Construtor para Novos Cadastros
    public CadastroAcaoJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.modoEdicao = false;
        btnSalvarAcao.setText("Cadastrar");
        txtQuantidade.setEnabled(false);
        
        JComboBox<TickersAcao> comboTickersAcao = new JComboBox<>();
        
        TickersAcao[] valores = TickersAcao.values();
        
        comboTickersAcao = new JComboBox<>(valores);
    }
    
    
    // Construtor para Edição
    public CadastroAcaoJD(java.awt.Frame parent, boolean modal, Acao acao)
    {
        this(parent, modal);
        this.acao = acao;
        this.modoEdicao = true;
          
        // método que aplica as mudanças visuais (Título e botão confirm)
        configurarParaEdicao();
        
        preencherCampos();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        txtPrecoUnitario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTicker = new javax.swing.JComboBox<>();
        btnSalvarAcao = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtPrecoUnitario.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtPrecoUnitarioPropertyChange(evt);
            }
        });

        jLabel2.setText("Ticker");

        jLabel3.setText("Descrição");

        jLabel4.setText("Quantidade");

        txtTicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ITUB4", "BBDC4", "BBAS3", "SANB11", "PETR4", "PETR3", "VALE3", "BEEF3", "JBSS3", "MGLU3", "AMER3", "VIVT3", "ELET3", "EGIE3", "HAPV3", "WEGE3" }));
        txtTicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTickerActionPerformed(evt);
            }
        });

        btnSalvarAcao.setText("Cadastrar");
        btnSalvarAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAcaoActionPerformed(evt);
            }
        });

        jLabel6.setText("Preço Unitário");

        lblTitulo.setText("Cadastrar Ação");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1))
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 111, Short.MAX_VALUE)
                                .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtTicker, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnSalvarAcao)
                                        .addGap(67, 67, 67)))))
                        .addGap(54, 54, 54))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(btnSalvarAcao)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTickerActionPerformed

    private void btnSalvarAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAcaoActionPerformed
        // TODO add your handling code here:
        
        if(acao == null)
            acao = new Acao();
        
        try{
              String tickerSelecionado = (String) txtTicker.getSelectedItem();
              
              Boolean jaCadastrado = adao.buscarAtivoJaCadastrado(tickerSelecionado);
              Boolean desincorporado = adao.verificarAtivoDesincorporado(tickerSelecionado);
              
              if(jaCadastrado && !modoEdicao) 
              {
                  JOptionPane.showMessageDialog(this, "Esse ativo já está cadastrado, vá para a seção de compra/venda/listagem para movimentar ele. ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                  return;
              }
              else if(desincorporado && !modoEdicao)
              {               
                 Ativo ativoEncontrado = adao.buscarAtivoDesincorporado(tickerSelecionado);
                 
                 ativoEncontrado.setDescricao((String) txtDescricao.getText().trim());
                   
                 adao.reencorporar(ativoEncontrado);
                 JOptionPane.showMessageDialog(this, "O Ativo " + ativoEncontrado.getTicker() + " foi reencorporado a sua carteira! ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                 this.dispose();
                 
              }
              else
              {
              if(tickerSelecionado == null || tickerSelecionado.isEmpty())
              {
                  JOptionPane.showMessageDialog(this, "Por favor, selecione um ticker.", "Erro", JOptionPane.ERROR_MESSAGE);
                  return;
              }
              
              String descricao = (String) txtDescricao.getText().trim();
              String precoStr = txtPrecoUnitario.getText();
              double precoUnitario = 0.0;
              
              try {
                precoStr = precoStr.replace(",", ".");

                precoUnitario = Double.parseDouble(precoStr);
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "O preço unitário inserido não é um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                return;
            }
              
              
              acao.setTicker(tickerSelecionado);
              acao.setDescricao(descricao);
              //acao.setQuantidade(quantidade);
              acao.setValorCompra(precoUnitario);
              acao.setValorAtual(precoUnitario);
              acao.setDataCompra(LocalDateTime.now());
              
              // Buscar dados adicionais no JSON
              DadosAcao dados = Utilitarios.buscarDadosAcao(tickerSelecionado);
              
              System.out.println(dados.getEmpresa());
              if (dados != null) {
                  acao.setNomeEmpresa(dados.getEmpresa());
              }
              
             
              adao.persist(acao);
              
  
              if(!modoEdicao)
              {
              JOptionPane.showMessageDialog(this, "Cadastro de " + tickerSelecionado
              + " realizado com sucesso! Agora este Ativo está incorporado a sua carteira.");
              //registrarTransacao(acao, quantidade);
              }
              else{
                  JOptionPane.showMessageDialog(this, "Atualização de " + tickerSelecionado
              + " realizada com sucesso!");
              }
              this.dispose();
              }
        }
        catch(Exception e)
        {
             
        }
    }//GEN-LAST:event_btnSalvarAcaoActionPerformed

    private void txtPrecoUnitarioPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtPrecoUnitarioPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecoUnitarioPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAcaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAcaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAcaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAcaoJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroAcaoJD dialog = new CadastroAcaoJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvarAcao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JComboBox<String> txtTicker;
    // End of variables declaration//GEN-END:variables

   private void preencherCampos(){
       if(this.acao != null){
           txtTicker.setSelectedItem(this.acao.getTicker());
           txtDescricao.setText(this.acao.getDescricao());
           txtQuantidade.setValue(this.acao.getQuantidade());
           txtPrecoUnitario.setText(String.valueOf(this.acao.getValorCompra()));
       }
   }
   private void configurarParaEdicao() {
       this.setTitle("Editar Ação - " + this.acao.getTicker());
       
       btnSalvarAcao.setText("Atualizar");
       
       //btnSalvarAcao.setBackground(java.awt.Color.Orange);
       
       // para que o ticker n seja modificável após o cadastro
       txtTicker.setEnabled(false);
       txtQuantidade.setEnabled(false);
       
   }
   
   /*
   private void registrarTransacao(Ativo acao, int quantidade){
        Transacao transacao = new Transacao();
        
        transacao.setQuantidade(quantidade);
        transacao.setPrecoUnitario(acao.getValorCompra());
        transacao.setData(LocalDateTime.now());
        transacao.setTipo(Transacao.TipoTransacao.COMPRA);
        transacao.setAtivo(acao);
        
        try {
            tdao.persist(transacao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
*/
}
