/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Acao;
import model.Ativo;
import model.FundoImobiliario;
import model.Transacao;
import modelDAO.AtivoDAO;
import modelDAO.TransacaoDAO;

/**
 *
 * @author vinic
 */
public class CadastroFiiJD extends javax.swing.JDialog {
    
    private boolean telaEdicao = false;
    private FundoImobiliario fii;
    
    
    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();

    /**
     * Creates new form CadastroFiiJD
     */
    public CadastroFiiJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.telaEdicao = false;
        txtQuantidade.setEnabled(false);
    }
    
    public CadastroFiiJD(java.awt.Frame parent, boolean modal, FundoImobiliario fii)
    {
        this(parent, modal);
        this.fii = fii;
        this.telaEdicao = true;
        preencherCampos();
        configurarParaEdicao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDescricao = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtTicker = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtTipoFundo = new javax.swing.JComboBox<>();
        btnCadastrarFii = new javax.swing.JButton();
        txtQuantidade = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtDescricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescricaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Ticker");

        jLabel2.setText("Descrição");

        jLabel3.setText("Quantidade");

        jLabel4.setText("Tipo de Fundo");

        txtTicker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MXRF11", "HGLG11", "KNRI11", "XPML11", "BRCR11" }));
        txtTicker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTickerActionPerformed(evt);
            }
        });

        txtTipoFundo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PAPEL", "TIJOLO", " " }));

        btnCadastrarFii.setText("Cadastrar");
        btnCadastrarFii.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarFiiActionPerformed(evt);
            }
        });

        jLabel6.setText("Preco Unitário");

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 12)); // NOI18N
        jLabel7.setText("Cadastrar Fundo Imobiliário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)))
                                .addGap(87, 87, 87)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtTicker, 0, 144, Short.MAX_VALUE))
                            .addComponent(txtTipoFundo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPrecoUnitario)
                            .addComponent(txtDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(86, 86, 86))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCadastrarFii)
                        .addGap(110, 110, 110))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTicker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtTipoFundo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCadastrarFii)
                .addGap(11, 11, 11))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTickerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTickerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTickerActionPerformed

    private void btnCadastrarFiiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarFiiActionPerformed
        // TODO add your handling code here:
      
        if (fii == null) {
            fii = new FundoImobiliario();
        }
               

        try {
            String tickerSelecionado = (String) txtTicker.getSelectedItem();
            
            if (tickerSelecionado == null || tickerSelecionado.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Por favor, selecione um ticker.", "Erro", JOptionPane.ERROR_MESSAGE);
                    return;
                }

            Boolean jaCadastrado = adao.buscarAtivoJaCadastrado(tickerSelecionado);
            Boolean desincorporado = adao.verificarAtivoDesincorporado(tickerSelecionado);
                       
            if (jaCadastrado && !telaEdicao) { // o ativo já está cadastrado e incorporado
                JOptionPane.showMessageDialog(this, "Esse ativo já está cadastrado, vá para a seção de compra/venda/listagem "
                        + "para movimentar ele. ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                return;
            } else if (desincorporado && !telaEdicao) { // o ativo encontra-se desincorporado
                Ativo ativoEncontrado = adao.buscarAtivoDesincorporado(tickerSelecionado);
                ativoEncontrado.setDescricao((String) txtDescricao.getText().trim());
                adao.reencorporar(ativoEncontrado);

                JOptionPane.showMessageDialog(this, "O Ativo " + ativoEncontrado.getTicker()
                        + " foi reencorporado a sua carteira! ", "Aviso", JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
                return;
            }            
            else { // o ativo não encontra-se cadastrado e tampouco incorporado
    
                // captura dos campos
                
                // ticker -> já foi capturado anteriormente
                String descricao = (String) txtDescricao.getText().trim();
                // quantidade (optei por não registrar quantidades na hora do cadastro)
                String precoStr = txtPrecoUnitario.getText();
                double precoUnitario = 0.0;
                try {
                    precoStr = precoStr.replace(",", ".");
                    precoUnitario = Double.parseDouble(precoStr);
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "O preço unitário inserido não é um número válido.", "Erro de Formato", JOptionPane.ERROR_MESSAGE);
                    e.printStackTrace();
                    return;
                }
                String tipoFundo = (String) txtTipoFundo.getSelectedItem();
                tipoFundo = tipoFundo.toLowerCase();
                

                fii.setTicker(tickerSelecionado);
                fii.setDescricao(descricao);
                fii.setValorCompra(precoUnitario);
                fii.setValorAtual(precoUnitario);
                
                if(tipoFundo.equals("tijolo")) {fii.setTipo(FundoImobiliario.tipoFundo.TIJOLO);}
                else if(tipoFundo.equals("papel")) {fii.setTipo(FundoImobiliario.tipoFundo.PAPEL);}
                
                fii.setDataCompra(LocalDateTime.now());
                
                try{
                adao.persist(fii);
                }catch(Exception e)
                {
                    e.printStackTrace();
                    return;
                }
            }

            if (!telaEdicao && !desincorporado) // cadastrado regularmente
            {
                JOptionPane.showMessageDialog(this, "Cadastro de " + tickerSelecionado
                        + " realizado com sucesso! Agora este Ativo está incorporado a sua carteira.");
            } else if (!telaEdicao && desincorporado) { // foi reencorporado a carteira
                this.dispose();
            } else if (telaEdicao) { // foi atualizado
                JOptionPane.showMessageDialog(this, "Atualização de " + tickerSelecionado
                        + " realizada com sucesso!");
            }

        } catch (Exception e) {

        }

        this.dispose();
    }//GEN-LAST:event_btnCadastrarFiiActionPerformed

    private void txtDescricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescricaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescricaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFiiJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFiiJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFiiJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFiiJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastroFiiJD dialog = new CadastroFiiJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarFii;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDescricao;
    private javax.swing.JTextField txtPrecoUnitario;
    private javax.swing.JSpinner txtQuantidade;
    private javax.swing.JComboBox<String> txtTicker;
    private javax.swing.JComboBox<String> txtTipoFundo;
    // End of variables declaration//GEN-END:variables
    private void preencherCampos(){
        if(this.fii != null){
           txtTicker.setSelectedItem(this.fii.getTicker());
           txtDescricao.setText(this.fii.getDescricao());
           txtQuantidade.setValue(this.fii.getQuantidade());
           txtPrecoUnitario.setText(String.valueOf(this.fii.getValorCompra()));
           txtTipoFundo.setSelectedItem(String.valueOf(this.fii.getFundo()));
        }
    }

    private void configurarParaEdicao(){
        this.setTitle("Editar FII - " + this.fii.getTicker());
        btnCadastrarFii.setText("Atualizar");
        
        txtTicker.setEnabled(false);
        txtQuantidade.setEnabled(false);
        
    }
    
    /*
    private void registrarTransacao(Ativo fii, int quantidade){
        Transacao transacao = new Transacao();
        
        transacao.setQuantidade(quantidade);
        transacao.setPrecoUnitario(fii.getValorCompra());
        transacao.setData(LocalDateTime.now());
        transacao.setTipo(Transacao.TipoTransacao.COMPRA);
        transacao.setAtivo(fii);
        
        try {
            tdao.persist(transacao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
*/
}
