/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Set;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Acao;
import model.Ativo;
import model.Transacao;
import modelDAO.AtivoDAO;
import modelDAO.TransacaoDAO;

/**
 *
 * @author vinic
 */
public class ComprarAcoesJD extends javax.swing.JDialog {
    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();
    /**
     * Creates new form EditarAcaoJD
     */

    public ComprarAcoesJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setTitle("Registrar Compra de Ação");
        carregarTickersNoComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTickers = new javax.swing.JComboBox<>();
        spnQuantidade = new javax.swing.JSpinner();
        btnRegistrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtPrecoUnitario = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ticker");

        jLabel2.setText("Quantidade");

        cmbTickers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jLabel3.setText("Preço Unitário");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(136, 136, 136))
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnQuantidade)
                    .addComponent(cmbTickers, 0, 87, Short.MAX_VALUE)
                    .addComponent(txtPrecoUnitario))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTickers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnRegistrar)
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        // TODO add your handling code here:
        String ticker = (String) cmbTickers.getSelectedItem();
        int quantidade = (int) spnQuantidade.getValue();
        String precoStr = txtPrecoUnitario.getText();
        double precoUnitario = 0.0;
        LocalDateTime dataAtual = LocalDateTime.now();
        
        precoStr = precoStr.replace(",", ".");
        precoUnitario = Double.parseDouble(precoStr);

        Ativo acao = adao.buscarAtivo(ticker);
        int quantidadeAntiga = acao.getQuantidade();

        int novaQuantidade = quantidadeAntiga += quantidade;

  
        acao.setQuantidade(novaQuantidade);
        acao.setValorCompra(precoUnitario);
        acao.setDataCompra(dataAtual);
        
        
        try {
            adao.persist(acao);
            registrarTransacao((Acao) acao, quantidade);
            JOptionPane.showMessageDialog(rootPane, "Compra de " + quantidade + " cotas de " + ticker +
                     " realizadas com sucesso! ");
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        this.dispose();
        
    }//GEN-LAST:event_btnRegistrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ComprarAcoesJD dialog = new ComprarAcoesJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbTickers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spnQuantidade;
    private javax.swing.JTextField txtPrecoUnitario;
    // End of variables declaration//GEN-END:variables
   
    private void carregarTickersNoComboBox() {
        Vector<String> listaDeTickers = new Vector<>();
        
        listaDeTickers.add("Selecione um Ticker");
        
        try{
            List<Ativo> listaAcoes = adao.listaAtivosPorTipo(Acao.class);
            
            for(Ativo ativo : listaAcoes) {
                listaDeTickers.add(ativo.getTicker());
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listaDeTickers);
            cmbTickers.setModel(model);
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tickers: " + 
                    e.getMessage(), "Erro de Carregamento", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    private void modificarQuantidadeAcao(String op, int quantia) {     /// c -> compra, v -> venda
        Ativo acao = adao.buscarAtivo((String) cmbTickers.getSelectedItem());
        int quantidadeAntiga = acao.getQuantidade();
        int novaQuantidade = 0;
        
        if(op.equals("c"))
        {
            novaQuantidade = quantidadeAntiga += quantia;
        }
        else if(op.equals("v"))
        {
            if(quantia > quantidadeAntiga) return;
            novaQuantidade = quantidadeAntiga - quantia;
        }
        acao.setQuantidade(novaQuantidade);
        
        try {
            adao.persist(acao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void registrarTransacao(Ativo acao, int quantidade){
        Transacao transacao = new Transacao();
        
        transacao.setQuantidade(quantidade);
        transacao.setPrecoUnitario(acao.getValorCompra());
        transacao.setData(LocalDateTime.now());
        transacao.setTipo(Transacao.TipoTransacao.COMPRA);
        transacao.setAtivo(acao);
        
        try {
            tdao.persist(transacao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

}
