/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.io.File;
import java.io.PrintWriter;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JOptionPane;
import model.Ativo;
import model.Transacao;
import modelDAO.AtivoDAO;
import modelDAO.TransacaoDAO;

/**
 *
 * @author vinic
 */
public class ExportarDadosJD extends javax.swing.JDialog {
    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();

    /**
     * Creates new form ExportarDadosJD
     */
    public ExportarDadosJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        checkAtivos = new javax.swing.JCheckBox();
        checkTransacoes = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnExportar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        checkAtivos.setText("Ativos");

        checkTransacoes.setText("Transações");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Selecione quais dados você deseja exportar ");

        btnExportar.setText("Exportar");
        btnExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExportarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(checkTransacoes)
                    .addComponent(checkAtivos)
                    .addComponent(btnExportar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(checkAtivos)
                .addGap(18, 18, 18)
                .addComponent(checkTransacoes)
                .addGap(38, 38, 38)
                .addComponent(btnExportar)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExportarActionPerformed
        // TODO add your handling code here:
        boolean expAtivos = false, expTransacoes = false;
        
        if(checkAtivos.isSelected()) {expAtivos = true;}
        if(checkTransacoes.isSelected()) {expTransacoes = true;}
        
        if(!expAtivos && !expTransacoes) {
            JOptionPane.showMessageDialog(this, "Selecione alguma das Opções para Exportar!");
            return; 
        }
        
        List<Ativo> ativos = adao.listaAtivos();
        List<Transacao> transacoes = tdao.listaTransacoes();
        
        System.out.println("Qtd de ativos: " + ativos.size());
        System.out.println("Qtd de transacoes: " + transacoes.size());

        
        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyyMMdd_HHmmss");
        String caminhoArquivo = "export/relatorio_investimentos_" + LocalDateTime.now().format(fmt) + ".csv";
        
        if(expAtivos || expTransacoes) {exportarAtivosParaCSV(ativos, transacoes, caminhoArquivo, expAtivos, expTransacoes);}
        
    }//GEN-LAST:event_btnExportarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExportarDadosJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExportarDadosJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExportarDadosJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExportarDadosJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ExportarDadosJD dialog = new ExportarDadosJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExportar;
    private javax.swing.JCheckBox checkAtivos;
    private javax.swing.JCheckBox checkTransacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
    
    private void exportarAtivosParaCSV(List<Ativo> ativos, List<Transacao> transacoes, String caminhoArquivo, boolean exportAtivos, boolean exportTransacoes) {
        try (PrintWriter writer = new PrintWriter(new File(caminhoArquivo))) {
            
            
            if(exportAtivos)
            {
            writer.println("=== ATIVOS ===");
            writer.println("Ticker, Descrição, Valor da Última Compra, Valor Atual, Quantidade, Data da Compra, Data da Exportação");
            
            for (Ativo a : ativos) {
                writer.printf("%s, %s, %.2f, %.2f, %d, %s, %s%n",
                        a.getTicker(),
                        a.getDescricao(),
                        a.getValorCompra(),
                        a.getValorAtual(),
                        a.getQuantidade(),
                        a.getDataCompra(),
                        LocalDateTime.now()
                );
            }
            
            writer.println();
            }
            
            if(exportTransacoes)
            {
            writer.println("=== TRANSACOES ===");
            writer.println("Tipo, Ticker, Quantidade, Preco Unitário, Movimentação Total, Data da Movimentação, Data da Exportação");
            
            for(Transacao t : transacoes){
                writer.printf("%s, %s, %d, %.2f, %.2f, %s%n",
                        t.getTipo(),
                        t.getAtivo().getTicker(),
                        t.getQuantidade(),
                        t.getPrecoUnitario(),
                        t.getPrecoUnitario() * t.getQuantidade(),
                        t.getData(),
                        LocalDateTime.now()
                );
            }
            }
            
            
            
            
        } catch (Exception e) {
            e.printStackTrace();
        }
    }



}
