/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Ativo;
import model.FundoImobiliario;
import modelDAO.AtivoDAO;

/**
 *
 * @author vinic
 */
public class ListaFiisJF extends javax.swing.JFrame {
    AtivoDAO adao = new AtivoDAO();

    /**
     * Creates new form ListaFiisJF
     */
    public ListaFiisJF() {
        initComponents();
        loadTabelaFiis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaFiis = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblListaFiis.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticker", "Tipo de Fundo", "Quantidade", "Descrição", "Valor Atual", "Valor de Compra", "Data da Compra (Última)"
            }
        ));
        jScrollPane1.setViewportView(tblListaFiis);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Fundos Imobiliários Cadastrados");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(186, 186, 186))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(btnEditar)
                        .addGap(28, 28, 28)
                        .addComponent(btnComprar)
                        .addGap(30, 30, 30)
                        .addComponent(btnVender)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnComprar)
                    .addComponent(btnVender))
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if (tblListaFiis.getSelectedRow() != -1) {
        String tickerFii = (String) tblListaFiis.getModel().getValueAt(tblListaFiis.getSelectedRow(), 0);
        Ativo ativoEncontrado = adao.buscarAtivo(tickerFii);

        if (ativoEncontrado != null) {
            
            // ✅ INÍCIO DO BLOCO DE VERIFICAÇÃO DE TIPO
            if(ativoEncontrado instanceof FundoImobiliario) { 
                
                // 1. Variável fiiEditar está dentro do escopo correto
                FundoImobiliario fiiEditar = (FundoImobiliario) ativoEncontrado; 
                
                int op_editar = JOptionPane.showConfirmDialog(rootPane, "Deseja editar dados referentes ao FII " + fiiEditar.getTicker() + "? ");
                
                if (op_editar == JOptionPane.YES_OPTION) {
                    try {
                        // 2. Passagem para o construtor
                        CadastroFiiJD dialogoFiiEditar = new CadastroFiiJD(this, true, fiiEditar);
                        dialogoFiiEditar.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(rootPane, "Erro ao abrir a janela de edição: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                
            } else {
                // Mensagem de erro se o objeto não for um FII (TIPO_ATIVO errado no banco)
                JOptionPane.showMessageDialog(rootPane, "O ativo encontrado não é um FII e não pode ser editado aqui.", "Tipo Incorreto", JOptionPane.WARNING_MESSAGE);
            }
            // ✅ FIM DO BLOCO DE VERIFICAÇÃO DE TIPO (CHAVE FINAL DENTRO DO if(ativoEncontrado != null))
        } else {
            // Ativo não encontrado (ativoEncontrado == null)
            JOptionPane.showMessageDialog(rootPane, "FII não encontrado. Verifique se o código está correto.", "Erro de Busca", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Selecione uma linha para editar.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
        ComprarFiisJD dialogoComprarFiis = new ComprarFiisJD(this, true);
        dialogoComprarFiis.setVisible(true);
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        VenderFiisJD dialogoVenderFiis = new VenderFiisJD(this, true);
        dialogoVenderFiis.setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFiisJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFiisJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFiisJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFiisJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFiisJF().setVisible(true);
            }
        });
    }
    
    public void loadTabelaFiis(){
        DefaultTableModel modelo = (DefaultTableModel) tblListaFiis.getModel();
        modelo.setNumRows(0);
        
        for(Ativo obj : adao.listaFiis())
        {
            // fazer o casting (mudar o tipo do dado) p/ Fundo Imobiliario -> Assim, consegue-se acessar o método getTipo(), que é da classe filha
            FundoImobiliario fii = (FundoImobiliario) obj;
            
            Object[] linha = {
                fii.getTicker(),
                fii.getQuantidade(),
                fii.getTipo(),
                fii.getDescricao(),
                fii.getValorAtual(),
                fii.getValorCompra(),
                fii.getDataCompra()
            };
              modelo.addRow(linha);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaFiis;
    // End of variables declaration//GEN-END:variables
}
