/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import model.Acao;
import model.Ativo;
import model.Transacao;
import modelDAO.AtivoDAO;
import modelDAO.TransacaoDAO;

/**
 *
 * @author vinic
 */
public class ListaAcoesJF extends javax.swing.JFrame {
    
    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();

    /**
     * Creates new form ListaAtivosJF
     */
    public ListaAcoesJF() {
        this.adao = adao;
        initComponents();
        loadTabelaAcoes();
        
        Timer timer = new Timer(5000, e-> loadTabelaAcoes());
        timer.start();
        
        jScrollPane1.setViewportView(tblListaAcoes);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaAcoes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btnEditarAcao = new javax.swing.JButton();
        btnComprarAcao = new javax.swing.JButton();
        btnVender = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        btnDesincorporar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblListaAcoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Ticker", "Quantidade", "Descrição", "Valor Atual", "Valor de Compra", "Última Compra", "Valor da Posição"
            }
        ));
        jScrollPane1.setViewportView(tblListaAcoes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Lista de Ações Cadastradas");

        btnEditarAcao.setText("Editar");
        btnEditarAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarAcaoActionPerformed(evt);
            }
        });

        btnComprarAcao.setText("Comprar");
        btnComprarAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarAcaoActionPerformed(evt);
            }
        });

        btnVender.setText("Vender");
        btnVender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenderActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnDesincorporar.setText("Desincorporar da Carteira");
        btnDesincorporar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDesincorporarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnVoltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(382, 382, 382))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnEditarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(btnComprarAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnVender, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(201, 201, 201)
                        .addComponent(btnDesincorporar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 997, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 484, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarAcao)
                    .addComponent(btnComprarAcao)
                    .addComponent(btnVender)
                    .addComponent(btnDesincorporar))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarAcaoActionPerformed
        // TODO add your handling code here:
    if (tblListaAcoes.getSelectedRow() != -1) {
        String tickerAcao = (String) tblListaAcoes.getModel().getValueAt(tblListaAcoes.getSelectedRow(), 0);
        Ativo ativoEncontrado = adao.buscarAtivo(tickerAcao);

        if (ativoEncontrado != null) {
            
            // ✅ INÍCIO DO BLOCO DE VERIFICAÇÃO DE TIPO
            if(ativoEncontrado instanceof Acao) { 
                
                // 1. Variável acaoEditar está dentro do escopo correto
                Acao acaoEditar = (Acao) ativoEncontrado; 
                
                int op_editar = JOptionPane.showConfirmDialog(rootPane, "Deseja editar dados referentes a Ação " + acaoEditar.getTicker() + "? ");
                
                if (op_editar == JOptionPane.YES_OPTION) {
                    try {
                        // 2. Passagem para o construtor
                        CadastroAcaoJD dialogoAcaoEditar = new CadastroAcaoJD(this, true, acaoEditar);
                        dialogoAcaoEditar.setVisible(true);
                    } catch (Exception e) {
                        e.printStackTrace();
                        JOptionPane.showMessageDialog(rootPane, "Erro ao abrir a janela de edição: " + e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
                        return;
                    }
                }
                
            } else {
                // Mensagem de erro se o objeto não for uma Acao (TIPO_ATIVO errado no banco)
                JOptionPane.showMessageDialog(rootPane, "O ativo encontrado não é uma Ação e não pode ser editado aqui.", "Tipo Incorreto", JOptionPane.WARNING_MESSAGE);
            }
            // ✅ FIM DO BLOCO DE VERIFICAÇÃO DE TIPO (CHAVE FINAL DENTRO DO if(ativoEncontrado != null))
        } else {
            // Ativo não encontrado (ativoEncontrado == null)
            JOptionPane.showMessageDialog(rootPane, "Ação não encontrada. Verifique se o Ticker está correto.", "Erro de Busca", JOptionPane.WARNING_MESSAGE);
        }
    } else {
        JOptionPane.showMessageDialog(rootPane, "Selecione uma linha para editar.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_btnEditarAcaoActionPerformed

    private void btnComprarAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarAcaoActionPerformed
        // TODO add your handling code here:
        ComprarAcoesJD dialogoComprarAcoes = new ComprarAcoesJD(this, true);
        dialogoComprarAcoes.setVisible(true);
    }//GEN-LAST:event_btnComprarAcaoActionPerformed

    private void btnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenderActionPerformed
        // TODO add your handling code here:
        VenderAcoesJD dialogoVenderAcoes = new VenderAcoesJD(this, true);
        dialogoVenderAcoes.setVisible(true);
    }//GEN-LAST:event_btnVenderActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnDesincorporarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDesincorporarActionPerformed
        // TODO add your handling code here:

        if (tblListaAcoes.getSelectedRow() != -1) {

            String tickerAcao = (String) tblListaAcoes.getModel().getValueAt(tblListaAcoes.getSelectedRow(), 0);
            Ativo ativoEncontrado = adao.buscarAtivo(tickerAcao);
            
            

            if (ativoEncontrado != null) {
                 int op_remover = JOptionPane.showConfirmDialog(rootPane, "VOCÊ TEM CERTEZA DE QUE DESEJA REMOVER O TICKER " + tickerAcao + " COMPLETAMENTE DE SUA CARTEIRA? ", "ATENÇÃO!", JOptionPane.OK_CANCEL_OPTION);
                 
                 if(op_remover == JOptionPane.OK_OPTION)
                 {
                     try{
                         int quantidade = ativoEncontrado.getQuantidade();
                         
                         registrarTransacao(ativoEncontrado, quantidade);
                         
                         adao.desincorporar(ativoEncontrado);
                         
                         JOptionPane.showMessageDialog(this, quantidade + " COTAS DE " + tickerAcao + " FORAM VENDIDAS E O ATIVO FOI DESINCORPORADO DE SUA CARTEIRA.");
                         
                     }catch(Exception e)
                     {
                         JOptionPane.showMessageDialog(this, "Erro ao tentar DESINCORPORAR O ATIVO");
                         e.printStackTrace();
                         return;
                     }
                 }
            
            }
        }
        else
        {
            JOptionPane.showMessageDialog(rootPane, "Selecione uma linha para editar.", "Atenção", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_btnDesincorporarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaAcoesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaAcoesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaAcoesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaAcoesJF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaAcoesJF().setVisible(true);
            }
        });
    }
    
    public void loadTabelaAcoes(){
        DefaultTableModel modelo = (DefaultTableModel) tblListaAcoes.getModel();
        modelo.setNumRows(0);
        
        List<Ativo> ativos = adao.listaAtivosPorTipo(Acao.class);
        
        for(Ativo obj : ativos){
            obj.atualizarValorAleatorio();
            
            String valorAtualFmt   = String.format("%.2f", obj.getValorAtual());
            String valorCompraFmt  = String.format("%.2f", obj.getValorCompra());
            String valorPosicaoFmt = String.format("%.2f", obj.getQuantidade() * obj.getValorAtual());
            
            Object[] linha = {
                obj.getTicker(),
                obj.getQuantidade(),
                obj.getDescricao(),
                valorAtualFmt,
                valorCompraFmt,
                obj.getDataCompra(),
                valorPosicaoFmt
            };
            modelo.addRow(linha);
        }
    }
    
    private void registrarTransacao(Ativo acao, int quantidade){
        Transacao transacao = new Transacao();
        
        transacao.setQuantidade(quantidade);
        transacao.setPrecoUnitario(acao.getValorCompra());
        transacao.setData(LocalDateTime.now());
        transacao.setTipo(Transacao.TipoTransacao.VENDA);
        transacao.setAtivo(acao);
        
        try {
            tdao.persist(transacao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComprarAcao;
    private javax.swing.JButton btnDesincorporar;
    private javax.swing.JButton btnEditarAcao;
    private javax.swing.JButton btnVender;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblListaAcoes;
    // End of variables declaration//GEN-END:variables
}
