/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.util.List;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Acao;
import model.Ativo;
import modelDAO.AtivoDAO;

/**
 *
 * @author vinic
 */
public class VenderAcoesJD extends javax.swing.JDialog {
     AtivoDAO adao = new AtivoDAO();
    /**
     * Creates new form VenderAcoesJD
     */
    public VenderAcoesJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarTickersNoComboBox();
        adicionarListenerAoTicker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTickers = new javax.swing.JComboBox<>();
        spnQuantidade = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ticker");

        jLabel2.setText("Quantidade");

        cmbTickers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbTickers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTickers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenderAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenderAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenderAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenderAcoesJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VenderAcoesJD dialog = new VenderAcoesJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTickers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner spnQuantidade;
    // End of variables declaration//GEN-END:variables

   private void carregarTickersNoComboBox() {
        Vector<String> listaDeTickers = new Vector<>();
        
        listaDeTickers.add("Selecione um Ticker");
        
        try{
            List<Ativo> listaAcoes = adao.listaAcoes();
            
            for(Ativo ativo : listaAcoes) {
                listaDeTickers.add(ativo.getTicker());
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listaDeTickers);
            cmbTickers.setModel(model);
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Erro ao carregar tickers: " + 
                    e.getMessage(), "Erro de Carregamento", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
   private void configurarLimiteDoSpinner(String tickerSelecionado) {
       if(tickerSelecionado == null || tickerSelecionado.isEmpty() || tickerSelecionado.equals("Selecione um Ticker")) {
           spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
           return;
       }
       
       Ativo ativoEncontrado = adao.buscarAtivo(tickerSelecionado);
       
       if(ativoEncontrado != null && ativoEncontrado instanceof Acao) {
           Acao acao = (Acao) ativoEncontrado;
           int quantidadeMaxima = acao.getQuantidade();
           
           spnQuantidade.setModel(new javax.swing.SpinnerNumberModel( // O SpinnerModel -> onde o JSpinner armazena seus limites
           (quantidadeMaxima > 0 ? 1 : 0), // valor inicial
           0,                              // mínimo
           quantidadeMaxima,               // Máximo
           1)                              // incremento (step-size)
           );
           
           spnQuantidade.setValue((quantidadeMaxima > 0 ? 1 : 0 ));
       } else {
           JOptionPane.showMessageDialog(this, "Erro ao registrar Venda", "Ticker Não Encontrado", JOptionPane.ERROR_MESSAGE);
       }
       
   }
   private void adicionarListenerAoTicker() {
       cmbTickers.addActionListener(new java.awt.event.ActionListener() {
           @Override
           public void actionPerformed(java.awt.event.ActionEvent evt) {
               
               String tickerSelecionado = (String) cmbTickers.getSelectedItem();
               
               configurarLimiteDoSpinner(tickerSelecionado);
           }
       });
   }

}
