/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.Ativo;
import model.FundoImobiliario;
import model.Transacao;
import modelDAO.AtivoDAO;
import modelDAO.TransacaoDAO;

/**
 *
 * @author vinic
 */
public class VenderFiisJD extends javax.swing.JDialog {
    AtivoDAO adao = new AtivoDAO();
    TransacaoDAO tdao = new TransacaoDAO();
    private FundoImobiliario fii;

    /**
     * Creates new form VenderFiisJD
     */
    public VenderFiisJD(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        carregarTickersNoComboBox();
        adicionarListenerAoTicker();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbTickers = new javax.swing.JComboBox<>();
        spnQuantidade = new javax.swing.JSpinner();
        btnConfirmarVendas = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Ticker");

        jLabel2.setText("Quantidade");

        cmbTickers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnConfirmarVendas.setText("Confirmar Vendas");
        btnConfirmarVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarVendasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTickers, 0, 91, Short.MAX_VALUE)
                    .addComponent(spnQuantidade))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(135, Short.MAX_VALUE)
                .addComponent(btnConfirmarVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbTickers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(spnQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(btnConfirmarVendas)
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConfirmarVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarVendasActionPerformed
        // TODO add your handling code here:
        String tickerSelecionado = (String) cmbTickers.getSelectedItem();
        int quantidade = (int) spnQuantidade.getValue();
        
        FundoImobiliario fii = (FundoImobiliario) adao.buscarAtivo(tickerSelecionado);
        
        if(fii.getQuantidade() >= quantidade)
        {
            fii.setQuantidade(fii.getQuantidade() - quantidade);
            
            try {
                adao.persist(fii);
                registrarTransacao(fii, quantidade);
            } catch (Exception ex) {
                Logger.getLogger(VenderFiisJD.class.getName()).log(Level.SEVERE, null, ex);
            }
            JOptionPane.showMessageDialog(rootPane, "Venda de " + quantidade + " cotas de " + tickerSelecionado +
                     " realizadas com sucesso! ");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "Você não possui cotas de " + 
                    tickerSelecionado + " suficientes para essa venda!");
        }
        
        this.dispose();
    }//GEN-LAST:event_btnConfirmarVendasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VenderFiisJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VenderFiisJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VenderFiisJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VenderFiisJD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VenderFiisJD dialog = new VenderFiisJD(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarVendas;
    private javax.swing.JComboBox<String> cmbTickers;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JSpinner spnQuantidade;
    // End of variables declaration//GEN-END:variables
     
    private void carregarTickersNoComboBox() {
        Vector<String> listaDeTickers = new Vector<>();
        
        listaDeTickers.add("Selecione um Ticker");
        
        try{
            List<Ativo> listaFiis = adao.listaAtivosPorTipo(FundoImobiliario.class);
            
            for(Ativo ativo : listaFiis){
                listaDeTickers.add(ativo.getTicker());
            }
            
            DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>(listaDeTickers);
            cmbTickers.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Erro ao carregar tickers: " + 
                    e.getMessage(), "Erro de Carregamento", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    
    private void configurarLimiteDoSpinner(String tickerSelecionado) {
        if(tickerSelecionado == null || tickerSelecionado.isEmpty() || 
                tickerSelecionado.equals("Selecione um Ticker")){
            spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
            return;
        }
        
        Ativo ativoEncontrado = adao.buscarAtivo(tickerSelecionado);
        
        if(ativoEncontrado != null && ativoEncontrado instanceof FundoImobiliario){
            FundoImobiliario fii = (FundoImobiliario) ativoEncontrado;
            int quantidadeMaxima = fii.getQuantidade();
            
            spnQuantidade.setModel(new javax.swing.SpinnerNumberModel(
            (quantidadeMaxima > 0 ? 1 : 0),
            0,
            quantidadeMaxima,
            1)
            );
            spnQuantidade.setValue((quantidadeMaxima > 0 ? 1 : 0));
            
        }else {
            JOptionPane.showMessageDialog(this, "Erro ao registrar Venda", "Ticker Não Encontrado", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void adicionarListenerAoTicker() {
        cmbTickers.addActionListener(new java.awt.event.ActionListener() {
            
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                String tickerSelecionado = (String) cmbTickers.getSelectedItem();
                
                configurarLimiteDoSpinner(tickerSelecionado);
            }
        });
    }

    private void registrarTransacao(Ativo fii, int quantidade){
        Transacao transacao = new Transacao();
        
        transacao.setQuantidade(quantidade);
        transacao.setPrecoUnitario(fii.getValorCompra());
        transacao.setData(LocalDateTime.now());
        transacao.setTipo(Transacao.TipoTransacao.VENDA);
        transacao.setAtivo(fii);
        
        try {
            tdao.persist(transacao);
        } catch (Exception ex) {
            Logger.getLogger(ComprarAcoesJD.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }

}
